# Generated by Django 5.0.4 on 2024-04-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartyName', models.CharField(max_length=100)),
                ('Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField()),
                ('GSTNo', models.CharField(max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
