# Generated by Django 5.0.4 on 2024-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_deliveryboymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(max_length=100)),
                ('Tax', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('PurchasePrice', models.CharField(max_length=100)),
                ('MRP', models.CharField(max_length=100)),
                ('SalsePrice', models.CharField(max_length=100)),
                ('MinQty', models.CharField(blank=True, max_length=100)),
                ('MaxQty', models.CharField(blank=True, max_length=100)),
                ('BarcodeNo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboymodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partymodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
