# Generated by Django 5.0.4 on 2024-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_purchaseentrymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(max_length=100)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('SubCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('Tax', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('PurchasePrice', models.CharField(max_length=100)),
                ('MRP', models.CharField(max_length=100)),
                ('MinQty', models.CharField(blank=True, max_length=100)),
                ('MaxQty', models.CharField(blank=True, max_length=100)),
                ('BarcodeNo', models.CharField(blank=True, max_length=100)),
                ('Quantity', models.CharField(blank=True, max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
    ]
