# Generated by Django 5.0.4 on 2024-04-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_nmmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoryModel',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='stockmodel',
            name='SubCategory',
        ),
    ]
