# Generated by Django 5.0.4 on 2024-04-24 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_subcategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='Unitname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 20, 7, 10, 120776)),
        ),
    ]
