# Generated by Django 5.0.4 on 2024-04-24 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_purchaseentrymodel_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmmodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 22, 28, 18, 605669)),
        ),
    ]
