# Generated by Django 5.0.4 on 2024-04-24 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_nmmodel_type_alter_purchaseentrymodel_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('DeliveryBoyName', models.CharField(blank=True, max_length=100, null=True)),
                ('TypeOfBusiness', models.CharField(blank=True, max_length=100, null=True)),
                ('DeliveryTime', models.TimeField()),
                ('InvoiceNo', models.CharField(blank=True, max_length=100, null=True)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2024, 4, 24, 23, 15, 35, 268943))),
                ('PartyName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 23, 15, 35, 268943)),
        ),
    ]
