# Generated by Django 5.0.4 on 2024-04-25 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_salesentrymodel_alter_purchaseentrymodel_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 7, 9, 18, 403519)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 7, 9, 18, 403519)),
        ),
    ]
