# Generated by Django 5.0.4 on 2024-04-25 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_stockmodel_type_alter_purchaseentrymodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 7, 45, 34, 679673)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 7, 45, 34, 679673)),
        ),
    ]
